---
- hosts: azure
  user: antonio
  vars:
    project_path: /home/antonio/proyecto
  tasks:
    - name: Crear directorio
      file:
        dest={{ project_path }}
        mode=0755
        recurse=yes
        state=directory
    - name: Añadir clave GPG para Mongo
      become: true
      become_method: sudo
      apt_key:
        keyserver: hkp://keyserver.ubuntu.com:80
        id: 9DA31620334BD75D9DCB49F368818C72E52529D4
        state: present
    - name: Añadir repo de mongo
      become: true
      become_method: sudo
      lineinfile:
        line: "deb [ arch=amd64 ] https://repo.mongodb.org/apt/ubuntu bionic/mongodb-org/4.0 multiverse"
        dest: /etc/apt/sources.list.d/mongodb-org-4.0.list
        state: present
        create: yes

    - name: Instalar MongoDB
      become: true
      become_method: sudo
      apt:
        name: mongodb-org
        state: present
        update_cache: yes

    - name: Arrancar servicio
      become: true
      become_method: sudo
      service:
        name: mongod
        state: started
    - name: install node
      shell: curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash - && sudo apt-get install -y nodejs
    - name: Clonar el repositorio
      git:
        repo: https://github.com/javiercabrera184/PCC2.git
        dest: "{{ project_path }}"
        force: yes
    - name: Instalar npm
      become: true
      become_method: sudo
      apt:
        pkg=npm state=present
    - name: Instala dependecias npm
      npm:
        path={{ project_path }}
    - name: Instala pm2
      become: true
      become_method: sudo
      npm:
        name: pm2
        global: yes
    - name: Elimina el proceso lanzado anteriormente
      command: pm2 delete PR
      ignore_errors: yes

    - name: Arrancar pm2
      command: pm2 start {{ project_path }}/app.js --name PR
