branches:
  only:
  - master
language: node_js
sudo: true
node_js:
- node
install:
- npm install mocha
- npm install supertest
- npm install express
- npm install assert
- npm install should
services:
  - mongodb
deploy:
  provider: heroku
  api_key:
    secure: sZXhv/EOlibgbyc4tpaAZCTrQ7HNT1BMbcIVU9JfBfq0rjgxryg5cPAJGp5mMkiqUCNIJe6Eyl4voJlhMuhrbComVGXu+WKKrvIvdnNSb4EZoUwBu9OJWQxPuaj85WntaUUfXLqV8ib/fms5GpN+DWrw2haOYnjy2lqptcQmdGaNXUMuDOhjNX1QavZNTXzxY7yfq5Jp2InSqIf64KeyuW3CbZmYR50RTyBmuXD7SfCy7LcFuzBR4s8gNWPM2hXhqvCVPCwHyozhCrPV7E+KrhDVD6iUDANS+d7K0cT7DZBwDlFz7H8KH7P3nskkgGWnfZavwA3ENE1lyAZL9UtbpQS2WFjV8kCMH4dgdeEYweP76rzBL1DnWLhu60NU8/c0/i3REYV2SeY2P1W0DN1YS5lsseMIk4bd8TnExaZDmwvYLPgGT/mHaqH+qkFU4Q2kKU0r3sjRiWaAU1HBsAyqnm2/kQRC/t1pEw5H86yI8v9POq2+CCTkNlFLrxsOlBb6Vz9bO6ht9L8rk7yECbTEcaqSrmvJskf49WUdU/9CemPQvIiex9q6ORXPtqVKqvbzVgB7mxsx6b6tm/JxnI6tf1HRca53UYZc8ir5aD6Ad/gL+P0qqt3dVLqPkwvdKrRwxbT2Pml6LOclTbE3ril4tBrGEoBbakav4KE/JhciTlE=
  strategy: git
  app: fast-sea-28858
  on:
    repo: javiercabrera184/PCC2
