
Vagrant.configure('2') do |config|


  config.vm.define "database" do |database|
    database.vm.box = 'azure'
    database.ssh.private_key_path = '~/.ssh/id_rsa' #copiamos clave ssh
    database.vm.provider :azure do |azure, override|

      # VARIABLES OBLIGATORIAS
      azure.tenant_id = ENV['AZURE_TENANT_ID']
      azure.client_id = ENV['AZURE_CLIENT_ID']
      azure.client_secret = ENV['AZURE_CLIENT_SECRET']
      azure.subscription_id = ENV['AZURE_SUBSCRIPTION_ID']

      # OPCIONALES
      azure.vm_name="hito5-database"
      azure.admin_username="antonio"
      azure.vm_image_urn="Canonical:UbuntuServer:18.04-LTS:latest"
      azure.location="francecentral"
      azure.resource_group_name="CC-Hito5"
      azure.tcp_endpoints = 27017 #abrimos solo puerto 27017
      azure.virtual_network_name="redprivada" #red virtual


    end
    #provisionamos
    database.vm.provision "ansible" do |ansible|
      ansible.compatibility_mode = "2.0"
      ansible.verbose = "v"
      ansible.playbook = "./playbook-database.yml"
    end
  end

  config.vm.define "app" do |app|
    app.vm.box = 'azure'
    app.ssh.private_key_path = '~/.ssh/id_rsa'
    app.vm.provider :azure do |azure, override|

      # VARIABLES OBLIGATORIAS
      azure.tenant_id = ENV['AZURE_TENANT_ID']
      azure.client_id = ENV['AZURE_CLIENT_ID']
      azure.client_secret = ENV['AZURE_CLIENT_SECRET']
      azure.subscription_id = ENV['AZURE_SUBSCRIPTION_ID']

      # OPCIONALES
      azure.vm_name="hito5-app"
      azure.admin_username="antonio"
      azure.vm_image_urn="Canonical:UbuntuServer:18.04-LTS:latest"
      azure.location="francecentral"
      azure.resource_group_name="CC-Hito5"
      azure.tcp_endpoints = [80,27017] #abrimos puertos 80 y 27017
      azure.virtual_network_name="redprivada" #usamos el mismo nombre de la red

    end
    #provisionamos
    app.vm.provision "ansible" do |ansible|
      ansible.compatibility_mode = "2.0"
      ansible.verbose = "v"
      ansible.playbook = "./playbook-app.yml"
    end
  end



end
